application: your-name-here
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1d"

libraries:
- name: jinja2
  version: latest

handlers:
- url: /_images
  static_dir: json/_images

- url: /_static
  static_dir: json/_static

- url: /_sources
  static_dir: json/_sources

- url: /_downloads
  static_dir: json/_downloads

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: sphinx.app
